# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        image: nginx:latest
        ports:
            - "${NGINX_PORT}:80"
            - "444:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ${PROJECT_FOLDER}:/var/www
            - ./logs:/var/log/nginx
        links:
            - php

    php:
        build: ./php
        container_name: project
        volumes:
            - ${PROJECT_FOLDER}:/var/www

    mariadb:
        image: mariadb
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${PMA_PORT}:80"
        environment:
          - PMA_HOST=mariadb
          - PMA_USER=root
          - PMA_PASSWORD=root
        depends_on:
            - mariadb